name: 'Update Index'
description: 'Update index file according to newly created article'
inputs:
  added:
    description: 'Paths to added articles'
    required: true
    default: '[]'
  removed:
    description: 'Paths to removed articles'
    required: true
    default: '[]'
  modified:
    description: 'Paths to modified articles'
    required: true
    default: './'
runs:
  using: 'node12'
  main: 'index.js'

  # outputs:
  # time: # id of output
  #   description: 'The time generation is done'